package com.farhan.bengkelnews.model

object BengkelData {

    val dataBengkel = listOf(
        Bengkel(
            1,
            "Penyebab Motor Matic Sering Mogok saat Digunakan Berkendara",
            "https://pict.sindonews.net/webp/960/salsabila/slider/2023/11/26261/penyebab-motor-matic-sering-mogok-saat-digunakan-berkendara-nax.webp",
            "Motor",
            "Motor Mogok",
            "Penyebab motor matic mogok bisa karena berbagai faktor. Tak jarang motor matic mogok karena pemilik tidak mengecek kondisi motornya dan melakukan service secara rutin.",
            "https://infografis.sindonews.com/photo/26261/penyebab-motor-matic-sering-mogok-saat-digunakan-berkendara-1698800413",
        ),
        Bengkel(
            2,
            "7 Alasan Pentingnya Perawatan Sepeda Motor Berkala",
            "https://pict.sindonews.net/webp/732/pena/news/2023/10/16/121/1226813/7-alasan-pentingnya-perawatan-sepeda-motor-berkala-cbs.webp",
            "Motor",
            "Perawatan Sepeda Motor",
            "Perawatan sepeda motor secara berkala adalah hal yang penting dilakukan para pemilik kendaraan. Sepeda motor merupakan alat transportasi yang umum digunakan oleh banyak orang di berbagai belahan dunia.",
            "https://otomotif.sindonews.com/read/1226813/121/7-alasan-pentingnya-perawatan-sepeda-motor-berkala-1697407810",
        ),
        Bengkel(
            3,
            "Bukan Genit, Ini Cara Mengatasi Headlamp LED Motor Berkedip-kedip",
            "https://pict.sindonews.net/webp/732/pena/news/2023/06/29/183/1140415/bukan-genit-ini-cara-mengatasi-headlamp-led-motor-berkedipkedip-xlp.webp",
            "Motor",
            "Lampu Kedip",
            "Headlamp atau lampu utama LED bukan hal yang asing lagi. Saat ini bisa dikatakan motor dan mobil baru kebanyakan sudah dilengkapi dengan headlamp LED.",
            "https://otomotif.sindonews.com/read/1140415/183/bukan-genit-ini-cara-mengatasi-headlamp-led-motor-berkedip-kedip-1688011562",
        ),
        Bengkel(
            4,
            "Milenial Karo Ikuti Pelatihan Tune Up Sepeda Motor",
            "https://pict.sindonews.net/webp/732/pena/news/2023/05/22/717/1104849/milenial-karo-ikuti-pelatihan-tune-up-sepeda-motor-abq.webp",
            "Motor",
            "Pelatihan Tune Up",
            "Para pemuda di Kabupaten Karo mendapatkan pelatihan tune up sepeda motor dari relawan Ganjar Milenial Center (GMC) Sumut. Kegiatan di Kecamatan Kabanjahe, Kabupaten Karo itu pun mendapatkan sambutan antusias dari kaum milenial.",
            "https://daerah.sindonews.com/read/1104849/717/milenial-karo-ikuti-pelatihan-tune-up-sepeda-motor-1684728351",
        ),
        Bengkel(
            5,
            "Viral Bengkel di Babakan Madang Getok Pemotor Rp2,7 Juta, Begini Duduk Perkaranya",
            "https://pict.sindonews.net/webp/732/pena/news/2023/05/02/170/1085985/viral-bengkel-di-babakan-madang-getok-pemotor-rp27-juta-begini-duduk-perkaranya-dpg.webp",
            " Kendaraan",
            "Bengkel Viral",
            "Beredar viral pengendara motor yang diduga menjadi korban aksi pemerasan oleh bengkel di wilayah Babakan Madang, Kabupaten Bogor. Polisi turun tangan untuk memastikan informasi tersebut.",
            "https://metro.sindonews.com/read/1085985/170/viral-bengkel-di-babakan-madang-getok-pemotor-rp27-juta-begini-duduk-perkaranya-1682989503",
        ),
        Bengkel(
            6,
            "Komponen RX King yang Harganya Mahal, Bisa Tembus Puluhan Juta Rupiah",
            "https://pict.sindonews.net/webp/732/pena/news/2022/09/15/121/885789/komponen-rx-king-yang-harganya-mahal-bisa-tembus-puluhan-juta-rupiah-lve.webp",
            "Motor",
            "Motor Mahal",
            "Komponen RX King yang harganya mahal ini perlu dicermati apabila Anda ingin merestorasi motor dua tak legendaris itu. Ya, saat ini Yamaha RX King kerap jadi incaran kolektor.",
            "https://otomotif.sindonews.com/read/885789/121/komponen-rx-king-yang-harganya-mahal-bisa-tembus-puluhan-juta-rupiah-1663222171",
        ),
        Bengkel(
            7,
            "Ini yang Dilakukan Mekanik Saat Servis Motor Anda di Bengkel",
            "https://pict.sindonews.net/webp/732/pena/news/2022/08/09/183/850571/ini-yang-dilakukan-mekanik-saat-servis-motor-anda-di-bengkel-jtk.webp",
            "Servis Motor",
            "Mekanik",
            "Perawatan berkala sepeda motor tidak boleh terlewat. Tentu, jika konsumen ingin kendaraan dalam performa baik. Jika terlewat sedikit, maka komponen sepeda motor yang seharusnya sudah diganti akan luput dari perhatian, bahkan akan membawa kerugian lebih besar",
            "https://otomotif.sindonews.com/read/850571/183/ini-yang-dilakukan-mekanik-saat-servis-motor-anda-di-bengkel-1660014538",
        ),
        Bengkel(
            8,
            "Inilah 4 Penyebab Motor Matik Tidak Kuat Nanjak, Pengendara Wajib Tau!",
            "https://pict.sindonews.net/webp/732/pena/news/2022/06/06/121/789829/inilah-4-penyebab-motor-matik-tidak-kuat-nanjak-pengendara-wajib-tau-qaw.webp",
            "Motor",
            "Motor Matik",
            "Sedikitnya ada empat penyebab motor matik tidak kuat nanjak. Sebagian pengendara tentu pernah mengalaminya. Dengan mengetahui penyebab motor matik tidak kuat nanjak, pengendara bisa terhindar dari kecelakaan.",
            "https://otomotif.sindonews.com/read/789829/121/inilah-4-penyebab-motor-matik-tidak-kuat-nanjak-pengendara-wajib-tau-1654495579",
        ),
        Bengkel(
            9,
            "CVT Motor Matic Alami Kerusakan, Ini 5 Tanda yang Perlu Diwaspadai",
            "https://pict.sindonews.net/webp/732/pena/news/2022/02/28/184/699377/cvt-motor-matic-alami-kerusakan-ini-5-tanda-yang-perlu-diwaspadai-rhd.webp",
            "Motor",
            "CVT Motor",
            "CVT motor matic masuk dalam kategori spare part atau komponen slow moving. Artinya CVT yang merupakan kepanjangan dari Continously Variable Transmission (CVT) butuh waktu yang cukup lama untuk diganti.",
            "https://otomotif.sindonews.com/read/699377/184/cvt-motor-matic-alami-kerusakan-ini-5-tanda-yang-perlu-diwaspadai-1646053357",
        ),
        Bengkel(
            10,
            "Sering Disalahartikan, Ini Perbedaan Modifikasi dan Custom pada Kendaraan",
            "https://pict.sindonews.net/webp/732/pena/news/2022/04/06/184/735341/sering-disalahartikan-ini-perbedaan-modifikasi-dan-custom-pada-kendaraan-fbm.webp",
            "Kendaraan",
            "Custom",
            "Sebagian orang tidak mengetahui perbedaan modifikasi dan custom pada kendaraan. Biasanya, orang akan beranggapan bahwa kedua istilah tersebut memiliki arti yang sama.",
            "https://otomotif.sindonews.com/read/735341/184/sering-disalahartikan-ini-perbedaan-modifikasi-dan-custom-pada-kendaraan-1649239483",
        ),
    )
}